// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnp6YaypJwJ3CWK9ZIRZpDx-iBfB_vr0I',
    appId: '1:71137853042:web:66838232ec58d6ac0c0ceb',
    messagingSenderId: '71137853042',
    projectId: 'appstructure1037',
    authDomain: 'appstructure1037.firebaseapp.com',
    storageBucket: 'appstructure1037.firebasestorage.app',
    measurementId: 'G-R6MF8MCCZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnNZJB62CtiOTkuvqdHyY_uf59fg1K2xc',
    appId: '1:71137853042:android:1d0974b5ca2cba6a0c0ceb',
    messagingSenderId: '71137853042',
    projectId: 'appstructure1037',
    storageBucket: 'appstructure1037.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQt77yqEAS2xrBXxReQhr5derT5bT67cI',
    appId: '1:71137853042:ios:4d86a0e2fea980a20c0ceb',
    messagingSenderId: '71137853042',
    projectId: 'appstructure1037',
    storageBucket: 'appstructure1037.firebasestorage.app',
    iosBundleId: 'com.example.appstructure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQt77yqEAS2xrBXxReQhr5derT5bT67cI',
    appId: '1:71137853042:ios:4d86a0e2fea980a20c0ceb',
    messagingSenderId: '71137853042',
    projectId: 'appstructure1037',
    storageBucket: 'appstructure1037.firebasestorage.app',
    iosBundleId: 'com.example.appstructure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnp6YaypJwJ3CWK9ZIRZpDx-iBfB_vr0I',
    appId: '1:71137853042:web:a92c6b19678a2ae40c0ceb',
    messagingSenderId: '71137853042',
    projectId: 'appstructure1037',
    authDomain: 'appstructure1037.firebaseapp.com',
    storageBucket: 'appstructure1037.firebasestorage.app',
    measurementId: 'G-NSP8KMEN5D',
  );
}
